version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.2.1
    container_name: nacos-standalone
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - ./env/nacos-standlone-mysql.env
      - ./env/nacos.env
    volumes:
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
      - ./nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
  mysql:
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    env_file:
      - ./env/mysql.env
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u my_user -p=${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10

